# Generated by Django 3.1.5 on 2021-01-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='books_pics')),
                ('eng_desc', models.TextField()),
                ('kor_desc', models.TextField()),
            ],
        ),
    ]
