# Generated by Django 3.1.5 on 2021-01-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0002_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
