# Generated by Django 3.1.5 on 2021-01-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0004_data_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_structure_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_data_structure', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='data_structure',
        ),
    ]
