# Generated by Django 3.1.5 on 2021-03-06 02:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0006_data_analytic_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='data_analytic_1',
        ),
        migrations.DeleteModel(
            name='data_structure_1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='eng_desc',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='kor_desc',
        ),
        migrations.RemoveField(
            model_name='track_of_mind',
            name='eng_desc',
        ),
        migrations.RemoveField(
            model_name='track_of_mind',
            name='kor_desc',
        ),
        migrations.AddField(
            model_name='book',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track_of_mind',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
